-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-09-14 20:34:56 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on
SPOOL brm_schema_output.txt

--student id: 35664029
--student name: Xin Ling Chong

DROP TABLE COMBINATION CASCADE CONSTRAINTS 
;

DROP TABLE CUSTOMER CASCADE CONSTRAINTS 
;

DROP TABLE EMPLOYEE CASCADE CONSTRAINTS 
;

DROP TABLE JOB CASCADE CONSTRAINTS 
;

DROP TABLE PURPOSE CASCADE CONSTRAINTS 
;

DROP TABLE QUOTE CASCADE CONSTRAINTS 
;

DROP TABLE TRAILER CASCADE CONSTRAINTS 
;

DROP TABLE TRAILER_TYPE CASCADE CONSTRAINTS 
;

DROP TABLE TRUCK CASCADE CONSTRAINTS 
;

DROP TABLE TRUCK_TYPE CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE COMBINATION 
    ( 
     combination_id        NUMBER (7)  NOT NULL , 
     combination_code      CHAR (3)  NOT NULL , 
     purpose_no            CHAR (3)  NOT NULL , 
     combination_hire_rate NUMBER (4)  NOT NULL , 
     truck_vin             CHAR (17)  NOT NULL , 
     trailer_code          CHAR (5)  NOT NULL 
    ) 
;

COMMENT ON COLUMN COMBINATION.combination_id IS 'Combination identifier (surrogate key)' 
;

COMMENT ON COLUMN COMBINATION.combination_code IS 'Combination code for a pair of truck and trailer' 
;

COMMENT ON COLUMN COMBINATION.purpose_no IS 'Purpose number' 
;

COMMENT ON COLUMN COMBINATION.combination_hire_rate IS 'Combination hire rate which determined by the truck/trailer combination and the purpose for which the combination will be used' 
;

COMMENT ON COLUMN COMBINATION.truck_vin IS 'Truck Vehicle Identification Number (VIN)' 
;

COMMENT ON COLUMN COMBINATION.trailer_code IS 'Trailer code' 
;

ALTER TABLE COMBINATION 
    ADD CONSTRAINT COMBINATION_PK PRIMARY KEY ( combination_id ) ;

ALTER TABLE COMBINATION 
    ADD CONSTRAINT COMBINATION_UQ UNIQUE ( combination_code , purpose_no ) ;

CREATE TABLE CUSTOMER 
    ( 
     customer_no            NUMBER (7)  NOT NULL , 
     customer_famname       VARCHAR2 (50)  NOT NULL , 
     customer_givname       VARCHAR2 (50)  NOT NULL , 
     customer_business_name VARCHAR2 (50) , 
     customer_address       VARCHAR2 (100)  NOT NULL , 
     customer_contact_no    CHAR (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CUSTOMER.customer_no IS 'Customer number' 
;

COMMENT ON COLUMN CUSTOMER.customer_famname IS 'Customer family name' 
;

COMMENT ON COLUMN CUSTOMER.customer_givname IS 'Customer given name' 
;

COMMENT ON COLUMN CUSTOMER.customer_business_name IS 'Customer business name' 
;

COMMENT ON COLUMN CUSTOMER.customer_address IS 'Customer address' 
;

COMMENT ON COLUMN CUSTOMER.customer_contact_no IS 'Customer contact number' 
;

ALTER TABLE CUSTOMER 
    ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY ( customer_no ) ;

CREATE TABLE EMPLOYEE 
    ( 
     employee_no          NUMBER (7)  NOT NULL , 
     employee_famname     VARCHAR2 (50)  NOT NULL , 
     employee_givname     VARCHAR2 (50)  NOT NULL , 
     employee_contact_no  CHAR (10)  NOT NULL , 
     employee_tax_file_no CHAR (9)  NOT NULL , 
     employee_salary      NUMBER (8,2)  NOT NULL , 
     employee_role        CHAR (3)  NOT NULL , 
     employee_licence_no  VARCHAR2 (20) , 
     manager_employee_no  NUMBER (7) 
    ) 
;

ALTER TABLE EMPLOYEE 
    ADD CONSTRAINT chk_employee_salary 
    CHECK (employee_salary BETWEEN 0 AND 999999.00) 
;

ALTER TABLE EMPLOYEE 
    ADD CONSTRAINT chk_employee_role 
    CHECK (employee_role IN ('DRV', 'MCH', 'MNG', 'TRD')) 
;

COMMENT ON COLUMN EMPLOYEE.employee_no IS 'Employee number' 
;

COMMENT ON COLUMN EMPLOYEE.employee_famname IS 'Employee family name' 
;

COMMENT ON COLUMN EMPLOYEE.employee_givname IS 'Employee given name' 
;

COMMENT ON COLUMN EMPLOYEE.employee_contact_no IS 'Employee contact number' 
;

COMMENT ON COLUMN EMPLOYEE.employee_tax_file_no IS 'Employee Tax File Number' 
;

COMMENT ON COLUMN EMPLOYEE.employee_salary IS 'Employee annual salary (0 to 999999.00)' 
;

COMMENT ON COLUMN EMPLOYEE.employee_role IS 'Employee role (DRV-Driver, MCH-Mechanic, MNG-Manager,TRD-Truck dispatcher)' 
;

COMMENT ON COLUMN EMPLOYEE.employee_licence_no IS 'Employee licence number' 
;

COMMENT ON COLUMN EMPLOYEE.manager_employee_no IS 'Employee number' 
;

ALTER TABLE EMPLOYEE 
    ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY ( employee_no ) ;

CREATE TABLE JOB 
    ( 
     job_no                 NUMBER (7)  NOT NULL , 
     job_pickup_datetime    DATE  NOT NULL , 
     job_dropoff_datetime   DATE  NOT NULL , 
     job_paid_status        CHAR (1)  NOT NULL , 
     job_revised_cost       NUMBER (8,2) , 
     driver_employee_no     NUMBER (7)  NOT NULL , 
     dispatcher_employee_no NUMBER (7)  NOT NULL , 
     quote_no               NUMBER (7)  NOT NULL , 
     combination_id         NUMBER (7)  NOT NULL , 
     mechanic_employee_no   NUMBER (7)  NOT NULL 
    ) 
;

ALTER TABLE JOB 
    ADD CONSTRAINT chk_job_paid_status 
    CHECK (job_paid_status IN ('N', 'Y')) 
;

COMMENT ON COLUMN JOB.job_no IS 'Job number' 
;

COMMENT ON COLUMN JOB.job_pickup_datetime IS 'Actual pickup date/time for job' 
;

COMMENT ON COLUMN JOB.job_dropoff_datetime IS 'Intended drop-off date/time for job' 
;

COMMENT ON COLUMN JOB.job_paid_status IS 'Job paid status (N-No, Y-Yes)' 
;

COMMENT ON COLUMN JOB.job_revised_cost IS 'Revised job cost which is different from the quoted cost' 
;

COMMENT ON COLUMN JOB.driver_employee_no IS 'Employee number' 
;

COMMENT ON COLUMN JOB.dispatcher_employee_no IS 'Employee number' 
;

COMMENT ON COLUMN JOB.quote_no IS 'Quote number' 
;

COMMENT ON COLUMN JOB.combination_id IS 'Combination identifier (surrogate key)' 
;

COMMENT ON COLUMN JOB.mechanic_employee_no IS 'Employee number' 
;
CREATE UNIQUE INDEX JOB__IDX ON JOB 
    ( 
     quote_no ASC 
    ) 
;

ALTER TABLE JOB 
    ADD CONSTRAINT JOB_PK PRIMARY KEY ( job_no ) ;

CREATE TABLE PURPOSE 
    ( 
     purpose_no   CHAR (3)  NOT NULL , 
     purpose_desc VARCHAR2 (50) 
    ) 
;

COMMENT ON COLUMN PURPOSE.purpose_no IS 'Purpose number' 
;

COMMENT ON COLUMN PURPOSE.purpose_desc IS 'Purpose description' 
;

ALTER TABLE PURPOSE 
    ADD CONSTRAINT PURPOSE_PK PRIMARY KEY ( purpose_no ) ;

CREATE TABLE QUOTE 
    ( 
     quote_no              NUMBER (7)  NOT NULL , 
     quote_prep_date       DATE  NOT NULL , 
     quote_cost            NUMBER (8,2)  NOT NULL , 
     quote_book_start_date DATE  NOT NULL , 
     quote_pickup_loc      VARCHAR2 (100)  NOT NULL , 
     quote_dropoff_loc     VARCHAR2 (100)  NOT NULL , 
     quote_job_purpose     VARCHAR2 (50)  NOT NULL , 
     employee_no           NUMBER (7)  NOT NULL , 
     customer_no           NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN QUOTE.quote_no IS 'Quote number' 
;

COMMENT ON COLUMN QUOTE.quote_prep_date IS 'The date on which the quote was prepared' 
;

COMMENT ON COLUMN QUOTE.quote_cost IS 'Quoted cost' 
;

COMMENT ON COLUMN QUOTE.quote_book_start_date IS 'Customer preferred start date for the booking' 
;

COMMENT ON COLUMN QUOTE.quote_pickup_loc IS 'Pickup location' 
;

COMMENT ON COLUMN QUOTE.quote_dropoff_loc IS 'Drop-off location' 
;

COMMENT ON COLUMN QUOTE.quote_job_purpose IS 'Purpose for the job' 
;

COMMENT ON COLUMN QUOTE.employee_no IS 'Employee number' 
;

COMMENT ON COLUMN QUOTE.customer_no IS 'Customer number' 
;

ALTER TABLE QUOTE 
    ADD CONSTRAINT QUOTE_PK PRIMARY KEY ( quote_no ) ;

CREATE TABLE TRAILER 
    ( 
     trailer_code              CHAR (5)  NOT NULL , 
     trailer_purchase_date     DATE  NOT NULL , 
     trailer_purchase_price    NUMBER (8,2)  NOT NULL , 
     trailer_load_capacity     NUMBER (6)  NOT NULL , 
     trailer_dimensions        VARCHAR2 (25)  NOT NULL , 
     trailer_decommission_date DATE , 
     trailer_manufacturer      VARCHAR2 (50)  NOT NULL , 
     trailer_model             VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN TRAILER.trailer_code IS 'Trailer code' 
;

COMMENT ON COLUMN TRAILER.trailer_purchase_date IS 'The date the business purchased the equipment for trailer' 
;

COMMENT ON COLUMN TRAILER.trailer_purchase_price IS 'Purchase price for trailer' 
;

COMMENT ON COLUMN TRAILER.trailer_load_capacity IS 'Load capacity for trailer (in kg)' 
;

COMMENT ON COLUMN TRAILER.trailer_dimensions IS 'Trailer dimensions' 
;

COMMENT ON COLUMN TRAILER.trailer_decommission_date IS 'Decommission date for trailer' 
;

COMMENT ON COLUMN TRAILER.trailer_manufacturer IS 'Trailer  manufacturer' 
;

COMMENT ON COLUMN TRAILER.trailer_model IS 'Trailer  model' 
;

ALTER TABLE TRAILER 
    ADD CONSTRAINT TRAILER_PK PRIMARY KEY ( trailer_code ) ;

CREATE TABLE TRAILER_TYPE 
    ( 
     trailer_manufacturer VARCHAR2 (50)  NOT NULL , 
     trailer_model        VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN TRAILER_TYPE.trailer_manufacturer IS 'Trailer  manufacturer' 
;

COMMENT ON COLUMN TRAILER_TYPE.trailer_model IS 'Trailer  model' 
;

ALTER TABLE TRAILER_TYPE 
    ADD CONSTRAINT TRAILER_TYPE_PK PRIMARY KEY ( trailer_manufacturer, trailer_model ) ;

CREATE TABLE TRUCK 
    ( 
     truck_vin               CHAR (17)  NOT NULL , 
     truck_rego_no           VARCHAR2 (15)  NOT NULL , 
     truck_km_total          NUMBER (8)  NOT NULL , 
     truck_km_last_service   NUMBER (8)  NOT NULL , 
     truck_purchase_date     DATE  NOT NULL , 
     truck_purchase_price    NUMBER (8,2)  NOT NULL , 
     truck_decommission_date DATE , 
     truck_manufacturer      VARCHAR2 (50)  NOT NULL , 
     truck_model             VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN TRUCK.truck_vin IS 'Truck Vehicle Identification Number (VIN)' 
;

COMMENT ON COLUMN TRUCK.truck_rego_no IS 'Truck  registration number' 
;

COMMENT ON COLUMN TRUCK.truck_km_total IS 'Total kilometres travelled for truck' 
;

COMMENT ON COLUMN TRUCK.truck_km_last_service IS 'Kilometre reading of the last service for truck' 
;

COMMENT ON COLUMN TRUCK.truck_purchase_date IS 'The date the business purchased the equipment for truck' 
;

COMMENT ON COLUMN TRUCK.truck_purchase_price IS 'Purchase price for truck' 
;

COMMENT ON COLUMN TRUCK.truck_decommission_date IS 'Decommission date for truck' 
;

COMMENT ON COLUMN TRUCK.truck_manufacturer IS 'Truck  manufacturer' 
;

COMMENT ON COLUMN TRUCK.truck_model IS 'Truck  model' 
;

ALTER TABLE TRUCK 
    ADD CONSTRAINT TRUCK_PK PRIMARY KEY ( truck_vin ) ;

CREATE TABLE TRUCK_TYPE 
    ( 
     truck_manufacturer VARCHAR2 (50)  NOT NULL , 
     truck_model        VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN TRUCK_TYPE.truck_manufacturer IS 'Truck  manufacturer' 
;

COMMENT ON COLUMN TRUCK_TYPE.truck_model IS 'Truck  model' 
;

ALTER TABLE TRUCK_TYPE 
    ADD CONSTRAINT TRUCK_TYPE_PK PRIMARY KEY ( truck_manufacturer, truck_model ) ;

ALTER TABLE JOB 
    ADD CONSTRAINT combination_job_fk FOREIGN KEY 
    ( 
     combination_id
    ) 
    REFERENCES COMBINATION 
    ( 
     combination_id
    ) 
;

ALTER TABLE QUOTE 
    ADD CONSTRAINT customer_quote_fk FOREIGN KEY 
    ( 
     customer_no
    ) 
    REFERENCES CUSTOMER 
    ( 
     customer_no
    ) 
;

ALTER TABLE EMPLOYEE 
    ADD CONSTRAINT employee_employee_fk FOREIGN KEY 
    ( 
     manager_employee_no
    ) 
    REFERENCES EMPLOYEE 
    ( 
     employee_no
    ) 
;

ALTER TABLE JOB 
    ADD CONSTRAINT employee_job_fk FOREIGN KEY 
    ( 
     driver_employee_no
    ) 
    REFERENCES EMPLOYEE 
    ( 
     employee_no
    ) 
;

ALTER TABLE JOB 
    ADD CONSTRAINT employee_job_fkv2 FOREIGN KEY 
    ( 
     dispatcher_employee_no
    ) 
    REFERENCES EMPLOYEE 
    ( 
     employee_no
    ) 
;

ALTER TABLE JOB 
    ADD CONSTRAINT employee_job_fkv3 FOREIGN KEY 
    ( 
     mechanic_employee_no
    ) 
    REFERENCES EMPLOYEE 
    ( 
     employee_no
    ) 
;

ALTER TABLE QUOTE 
    ADD CONSTRAINT employee_quote_fk FOREIGN KEY 
    ( 
     employee_no
    ) 
    REFERENCES EMPLOYEE 
    ( 
     employee_no
    ) 
;

ALTER TABLE COMBINATION 
    ADD CONSTRAINT purpose_combination_fk FOREIGN KEY 
    ( 
     purpose_no
    ) 
    REFERENCES PURPOSE 
    ( 
     purpose_no
    ) 
;

ALTER TABLE JOB 
    ADD CONSTRAINT quote_job_fk FOREIGN KEY 
    ( 
     quote_no
    ) 
    REFERENCES QUOTE 
    ( 
     quote_no
    ) 
;

ALTER TABLE COMBINATION 
    ADD CONSTRAINT trailer_combination_fk FOREIGN KEY 
    ( 
     trailer_code
    ) 
    REFERENCES TRAILER 
    ( 
     trailer_code
    ) 
;

ALTER TABLE TRAILER 
    ADD CONSTRAINT trailer_type_trailer_fk FOREIGN KEY 
    ( 
     trailer_manufacturer,
     trailer_model
    ) 
    REFERENCES TRAILER_TYPE 
    ( 
     trailer_manufacturer,
     trailer_model
    ) 
;

ALTER TABLE COMBINATION 
    ADD CONSTRAINT truck_combination_fk FOREIGN KEY 
    ( 
     truck_vin
    ) 
    REFERENCES TRUCK 
    ( 
     truck_vin
    ) 
;

ALTER TABLE TRUCK 
    ADD CONSTRAINT truck_type_truck_fk FOREIGN KEY 
    ( 
     truck_manufacturer,
     truck_model
    ) 
    REFERENCES TRUCK_TYPE 
    ( 
     truck_manufacturer,
     truck_model
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             1
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

set echo OFF
spool OFF